# These are supported funding model platforms

custom: ['https://monero/wallet/837ooBb4LrdGKd2qbzEsjt4SgdG9oCLJgjozRCyszB474pNrEzAftYdPL8EA75h7NqP4Zxmp2ikR3eggLeWcViCMVJxYpQ8', 'https://bitcoin/wallet/1GWxFbfqHcMR4FEKy2P1sayPkFByGKGwCK', 'https://ethereum/wallet/0x58dC9585BE36e855bA30609909f7D4Ef11313ee1']
